# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time', models.DateTimeField()),
                ('picture', models.ImageField(height_field=100, upload_to=True, width_field=200)),
                ('description', models.TextField(default='None', max_length=300)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('thumbnail', models.ImageField(height_field=100, upload_to=False, width_field=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True)),
                ('profile_pic', models.ImageField(height_field=30, upload_to=True, width_field=60)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.User'),
        ),
    ]
