# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(default='N/A', max_length=30),
        ),
    ]
