# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20180315_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='play.User'),
        ),
    ]
