# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_auto_20180315_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
