# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-20 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_auto_20180316_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
