# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_auto_20180320_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='host',
        ),
        migrations.RemoveField(
            model_name='team',
            name='follower',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
