# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0015_auto_20180320_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.CharField(default='N/A', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
